drop table t_shopping_member;
drop table t_shopping_goods;
drop table t_goods_detail_image;
drop table t_shopping_order;
drop table t_shopping_cart;


--------------------------------------------------------
--  DDL for Tablble GOODS (상품 테이블)
-- 변경사항 : GOODS_CREDATE -> GOODS_ENTER_DATE로 변경
--------------------------------------------------------

  CREATE TABLE "GOODS" 
   (GOODS_ID NUMBER(20,0) primary key, 
	GOODS_SORT VARCHAR2(50), 
	GOODS_TITLE VARCHAR2(100), 
	GOODS_WRITER VARCHAR2(50), 
	GOODS_PUBLISHER VARCHAR2(50), 
	GOODS_PRICE NUMBER(10,0), 
	GOODS_SALES_PRICE NUMBER(10,0), 
	GOODS_POINT NUMBER(10,0), 
	GOODS_PUBLISHED_DATE DATE, 
	GOODS_TOTAL_PAGE NUMBER(5,0), 
	GOODS_ISBN VARCHAR2(50), 
	GOODS_DELIVERY_PRICE NUMBER(10,0), 
	GOODS_DELIVERY_DATE DATE, 
	GOODS_STATUS VARCHAR2(50), 
	GOODS_INTRO VARCHAR2(2000), 
	GOODS_WRITER_INTRO VARCHAR2(2000), 
	GOODS_PUBLISHER_COMMENT VARCHAR2(2000), 
	GOODS_RECOMMENDATION VARCHAR2(2000), 
	GOODS_CONTENTS_ORDER CLOB, 
	GOODS_ENTER_DATE DATE DEFAULT sysdate
   ) ;
   COMMENT ON COLUMN GOODS.GOODS_ID is '상품번호';
   COMMENT ON COLUMN GOODS.GOODS_SORT is '상품종류';
   COMMENT ON COLUMN GOODS.GOODS_TITLE is '상품제목';
   COMMENT ON COLUMN GOODS.GOODS_WRITER is '저자이름';
   COMMENT ON COLUMN GOODS.GOODS_PUBLISHER is '출판사이름';
   COMMENT ON COLUMN GOODS.GOODS_PRICE is '상품정가';
   COMMENT ON COLUMN GOODS.GOODS_SALES_PRICE is '상품판매가격';
   COMMENT ON COLUMN GOODS.GOODS_POINT is '상품포인트';
   COMMENT ON COLUMN GOODS.GOODS_PUBLISHED_DATE is '상품출판일';
   COMMENT ON COLUMN GOODS.GOODS_TOTAL_PAGE is '상품총페이지수';
   COMMENT ON COLUMN GOODS.GOODS_ISBN is 'isbn번호';
   COMMENT ON COLUMN GOODS.GOODS_DELIVERY_PRICE is '배송비';
   COMMENT ON COLUMN GOODS.GOODS_DELIVERY_DATE is '상품배송일';
   COMMENT ON COLUMN GOODS.GOODS_STATUS is '상품분류';
   COMMENT ON COLUMN GOODS.GOODS_INTRO is '상품소개';
   COMMENT ON COLUMN GOODS.GOODS_WRITER_INTRO is '저자소개';
   COMMENT ON COLUMN GOODS.GOODS_PUBLISHER_COMMENT is '출판사평';
   COMMENT ON COLUMN GOODS.GOODS_RECOMMENDATION is '상품추천사';
   COMMENT ON COLUMN GOODS.GOODS_CONTENTS_ORDER is '상품목차';
   COMMENT ON COLUMN GOODS.GOODS_ENTER_DATE is '상품입고일';
--------------------------------------------------------
--  DDL for Table GOODS_IMAGE  (상품 이미지 테이블)
-- 변경 사항 : CREDATE -> REG_DATE
--------------------------------------------------------

  CREATE TABLE GOODS_IMAGE
   (IMAGE_ID NUMBER(20,0) primary key, 
	GOODS_ID NUMBER(20,0), 
	FILENAME VARCHAR2(50), 
	REG_ID VARCHAR2(20), 
	FILETYPE VARCHAR2(40), 
	REG_DATE DATE DEFAULT sysdate
   );
   COMMENT ON COLUMN GOODS_IMAGE.IMAGE_ID is '이미지번호';
   COMMENT ON COLUMN GOODS_IMAGE.GOODS_ID is '상품번호';
   COMMENT ON COLUMN GOODS_IMAGE.FILENAME is '이미지파일명';
   COMMENT ON COLUMN GOODS_IMAGE.REG_ID is '등록자아이디';
   COMMENT ON COLUMN GOODS_IMAGE.FILETYPE is '이미지파일종류';
   COMMENT ON COLUMN GOODS_IMAGE.REG_DATE is '등록일';
--------------------------------------------------------
--  DDL for Table MEMBER (멤버 테이블)
--  변경사항 : SMSSTS_YN -> SMS_YN, EAMILSTS_YN -> EMAIL_YN, ROADARRDESS -> ROAD_ADDRESS, JIBUNADDRESS -> JIBUN_ADDRESS
-- NAMISJIADDRESS -> DETAIL_ADDRESS, MEMBER_BIRTH_Y -> BIRTH_YEAR, MEMBER_BIRTH_M-> BIRTH_MONTH, MEMBER_BITH_D -> MEMBER_BIRTH_DAY
-- MEMBER_BIRTH_GN 제거
--------------------------------------------------------

  CREATE TABLE MEMBER
   (MEMBER_ID VARCHAR2(20) primary key, 
	MEMBER_PW VARCHAR2(30), 
	MEMBER_NAME VARCHAR2(50), 
	MEMBER_GENDER VARCHAR2(10), 
	TEL1 VARCHAR2(20), 
	TEL2 VARCHAR2(20), 
	TEL3 VARCHAR2(20), 
	HP1 VARCHAR2(20), 
	HP2 VARCHAR2(20), 
	HP3 VARCHAR2(20), 
	SMS_YN VARCHAR2(20), 
	EMAIL1 VARCHAR2(20), 
	EMAIL2 VARCHAR2(20), 
	EMAIL_YN VARCHAR2(20), 
	ZIPCODE VARCHAR2(20), 
	ROAD_ADDRESS VARCHAR2(500), 
	JIBUN_ADDRESS VARCHAR2(500), 
	DETAIL_ADDRESS VARCHAR2(500), 
	BIRTH_YEAR VARCHAR2(20), 
	BIRTH_MONTH VARCHAR2(20), 
	BIRTH_DAY VARCHAR2(20), 
	JOIN_DATE DATE DEFAULT sysdate, 
	DELETE_YN VARCHAR2(20) DEFAULT 'N'
   );
    COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_ID" IS '회원아이디';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_PW" IS '비밀번호';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_NAME" IS '회원이름';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_GENDER" IS '성별';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."TEL1" IS '유선전화번호1';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."TEL2" IS '유선전화번호2';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."TEL3" IS '유선전화버호3';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."HP1" IS '휴대폰번호1';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."HP2" IS '휴대폰번호2';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."HP3" IS '휴대폰번호3';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."SMS_YN" IS 'SMS메시지수신여부';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."EMAIL1" IS '이메일주소1';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."EMAIL2" IS '이메일주소2';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."EMAIL_YN" IS '이메일수신여부';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."ZIPCODE" IS '우편번호';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."ROAD_ADDRESS" IS '도로명주소';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."JIBUN_ADDRESS" IS '지번주소';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."DETAIL_ADDRESS" IS '나머지주소';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."BIRTH_YEAR" IS '생년월일년';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."BIRTH_MONTH" IS '생년월일월';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."BIRTH_DAY" IS '생년월일일';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."JOIN_DATE" IS '회원가입일자';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."DELETE_YN" IS '회원탈퇴유무';
--------------------------------------------------------
--  DDL for Table ORDER
-- 변경 사항 : PAY_ORDERER_HP_NUM => PAY_ORDERER_HP
--------------------------------------------------------

  CREATE TABLE ORDERS
   (ORDER_SEQ_NUM NUMBER(20,0) primary key, 
	ORDER_ID NUMBER(20,0), 
	MEMBER_ID VARCHAR2(20), 
	GOODS_ID NUMBER(20,0), 
	ORDERER_NAME VARCHAR2(50), 
	GOODS_TITLE VARCHAR2(100), 
	ORDER_GOODS_QTY NUMBER(5,0), 
	GOODS_SALES_PRICE NUMBER(5,0), 
	GOODS_FILENAME VARCHAR2(60), 
	RECEIVER_NAME VARCHAR2(50), 
	RECEIVER_HP1 VARCHAR2(20), 
	RECEIVER_HP2 VARCHAR2(20), 
	RECEIVER_HP3 VARCHAR2(20), 
	RECEIVER_TEL1 VARCHAR2(20), 
	RECEIVER_TEL2 VARCHAR2(20), 
	RECEIVER_TEL3 VARCHAR2(20), 
	DELIVERY_ADDRESS VARCHAR2(500), 
	DELIVERY_METHOD VARCHAR2(40), 
	DELIVERY_MESSAGE VARCHAR2(300), 
	GIFT_WRAPPING VARCHAR2(20), 
	PAY_METHOD VARCHAR2(200), 
	CARD_COM_NAME VARCHAR2(50), 
	CARD_PAY_MONTH VARCHAR2(20), 
	PAY_ORDERER_HP VARCHAR2(20), 
	DELIVERY_STATE VARCHAR2(20) DEFAULT 'delivery_prepared', 
	PAY_ORDER_TIME DATE DEFAULT sysdate, 
	ORDERER_HP VARCHAR2(50)
   );
    COMMENT ON COLUMN "SCOTT"."ORDERS"."ORDER_SEQ_NUM" IS '주문상품일련번호';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."ORDER_ID" IS '주문번호';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."MEMBER_ID" IS '주문자아이디';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."GOODS_ID" IS '상품이름';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."ORDERER_NAME" IS '주문수량';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."GOODS_TITLE" IS '상품이름';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."ORDER_GOODS_QTY" IS '주문수량';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."GOODS_SALES_PRICE" IS '상품판매가격';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."GOODS_FILENAME" IS '상품이미지파일이름';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."RECEIVER_NAME" IS '수령자이름';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."RECEIVER_HP1" IS '수령자휴대폰번호1';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."RECEIVER_HP2" IS '수령자휴대폰번호2';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."RECEIVER_HP3" IS '수령자휴대폰번호3';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."RECEIVER_TEL1" IS '수령자유선번호1';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."RECEIVER_TEL2" IS '수령자유선번호2';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."RECEIVER_TEL3" IS '수령자유선번호3';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."DELIVERY_ADDRESS" IS '배송주소';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."DELIVERY_METHOD" IS '배송방법';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."DELIVERY_MESSAGE" IS '부재 시 전달 메시지';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."GIFT_WRAPPING" IS '상품포장여부';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."PAY_METHOD" IS '결제방법';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."CARD_COM_NAME" IS '결제카드회사이름';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."CARD_PAY_MONTH" IS '할부개월수';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."PAY_ORDERER_HP" IS '휴대폰결제번호';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."DELIVERY_STATE" IS '배송상태';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."PAY_ORDER_TIME" IS '결제시간';
   COMMENT ON COLUMN "SCOTT"."ORDERS"."ORDERER_HP" IS '주문자휴대폰번호';
--------------------------------------------------------
--  DDL for Table CART
-- 변경 사항 : del_yn -> delete_yn , credate -> reg_date
--------------------------------------------------------

  CREATE TABLE CART
   (CART_ID NUMBER(10,0) primary key, 
	GOODS_ID NUMBER(20,0), 
	MEMBER_ID VARCHAR2(20 BYTE), 
	DELETE_YN VARCHAR2(20 BYTE) DEFAULT 'N', 
	REG_DATE DATE DEFAULT sysdate, 
	CART_GOODS_QTY NUMBER(4,0) DEFAULT 1
   );
   
   COMMENT ON COLUMN "SCOTT"."CART"."CART_ID" IS '장바구니번호';
   COMMENT ON COLUMN "SCOTT"."CART"."GOODS_ID" IS '상품번호';
   COMMENT ON COLUMN "SCOTT"."CART"."MEMBER_ID" IS '회원아이디';
   COMMENT ON COLUMN "SCOTT"."CART"."DELETE_YN" IS '장바구니삭제여부';
   COMMENT ON COLUMN "SCOTT"."CART"."REG_DATE" IS '생성일자';
   COMMENT ON COLUMN "SCOTT"."CART"."CART_GOODS_QTY" IS '상품수량';